import { VisualTestSnapshot } from '../../types/regression';

export const INITIAL_TEST_SNAPSHOTS: VisualTestSnapshot[] = [
  {
    id: 'snap-btn-prim',
    name: 'PressButton Primitives & Deboss Relief',
    component: '<PressButton />',
    category: 'primitives',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.02,
    baselineTimestamp: '2026-10-08 04:12 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Primary press button with 600gsm deboss shadow and tactile active transform.'
  },
  {
    id: 'snap-specimen-card',
    name: 'SpecimenCard (Zero-Pill Typography)',
    component: '<SpecimenCard />',
    category: 'components',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.04,
    baselineTimestamp: '2026-10-08 04:15 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Verifies zero-pill metadata discipline, typographic measure 65ch, and hairline divider.'
  },
  {
    id: 'snap-imposition-grid',
    name: '16-Page Signature Imposition Sheet',
    component: '<ImpositionSheet />',
    category: 'primitives',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.01,
    baselineTimestamp: '2026-10-08 04:18 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Verifies CMYK density target bar, registration crosshairs, and 3mm trim guides.'
  },
  {
    id: 'snap-theme-dark-litho',
    name: 'Theme Parity: Inking Well & Darkroom',
    component: '<ThemeBoundary dark-litho />',
    category: 'themes',
    viewport: 'desktop-1440',
    theme: 'dark-litho',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.08,
    baselineTimestamp: '2026-10-08 04:22 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Optical compensation on dark obsidian zinc plate with silvered text contrast WCAG AAA.'
  },
  {
    id: 'snap-fail-offline',
    name: 'Failure State 01: Offline Press Queue',
    component: '<OfflineState />',
    category: 'failures',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.03,
    baselineTimestamp: '2026-10-08 04:25 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Protects offline warning banner and local cache ledger against accidental CSS regressions.'
  },
  {
    id: 'snap-fail-timeout',
    name: 'Failure State 02: 30s RIP Timeout Matrix',
    component: '<TimeoutState />',
    category: 'failures',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.05,
    baselineTimestamp: '2026-10-08 04:30 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Ensures yellow separation stall indicator and recovery radio options remain legible.'
  },
  {
    id: 'snap-fail-server',
    name: 'Failure State 03: 500 Imposition Engine Crash',
    component: '<ServerErrorState />',
    category: 'failures',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.02,
    baselineTimestamp: '2026-10-08 04:35 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Incident reference token and manual routing fallback safeguards.'
  },
  {
    id: 'snap-fail-invalid',
    name: 'Failure State 04: 422 Pre-Flight Bleed Error',
    component: '<InvalidDataState />',
    category: 'failures',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.03,
    baselineTimestamp: '2026-10-08 04:40 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: '3-point preflight inspection diagnostics (bleed, CMYK profile, outlined fonts).'
  },
  {
    id: 'snap-fail-session',
    name: 'Failure State 05: Expired Session Lock',
    component: '<ExpiredSessionState />',
    category: 'failures',
    viewport: 'desktop-1440',
    theme: 'light-cotton',
    status: 'passed',
    mismatchPercentage: 0.0,
    deltaE: 0.01,
    baselineTimestamp: '2026-10-08 04:45 PST',
    currentTimestamp: '2026-10-08 05:30 PST',
    diffRegionsCount: 0,
    notes: 'Guarantees zero-data-loss state lock modal during 45min operator idle timeout.'
  }
];
