import { ThemeConfig } from '../types/tokens';

export const THEMES: Record<string, ThemeConfig> = {
  'light-cotton': {
    id: 'light-cotton',
    name: 'Archival Cotton (600gsm)',
    description: 'Clean unbleached cotton paper stock with cast-lead black ink and subtle bronze accents.',
    stockType: 'Mohawk Superfine Smooth (352gsm / 130lb)',
    inkProfile: 'Cold-Set Lampblack + Heidelberg Vermilion Spot',
    cssVariables: {
      '--surface-canvas': '#FAF8F5',
      '--surface-card': '#FFFFFF',
      '--surface-muted': '#F2EFE9',
      '--surface-raised': '#FFFFFF',
      '--surface-overlay': 'rgba(250, 248, 245, 0.95)',
      '--border-hairline': 'rgba(40, 38, 35, 0.12)',
      '--border-strong': 'rgba(40, 38, 35, 0.35)',
      '--border-focus': '#966324',
      '--ink-primary': '#141413',
      '--ink-secondary': '#3F3E3B',
      '--ink-muted': '#72706A',
      '--ink-accent': '#966324',
      '--color-primary': '#141413',
      '--color-primary-hover': '#2C2B28',
      '--color-primary-fg': '#FAF8F5',
      '--color-danger': '#B8321B',
      '--color-warning': '#D97706',
      '--color-success': '#1D4537',
      '--press-registration': '#141413',
      '--press-bleed': 'rgba(184, 50, 27, 0.25)'
    }
  },
  'dark-litho': {
    id: 'dark-litho',
    name: 'Inking Well & Darkroom',
    description: 'Deep zinc lithographic plate aesthetic with silvered type and high-gamut process highlights.',
    stockType: 'Arches Black Velin (300gsm)',
    inkProfile: 'UV-Cured Process Cyan & Silver Metallic Dust',
    cssVariables: {
      '--surface-canvas': '#0F1012',
      '--surface-card': '#17191C',
      '--surface-muted': '#202327',
      '--surface-raised': '#26292E',
      '--surface-overlay': 'rgba(15, 16, 18, 0.95)',
      '--border-hairline': 'rgba(255, 255, 255, 0.12)',
      '--border-strong': 'rgba(255, 255, 255, 0.3)',
      '--border-focus': '#0099CC',
      '--ink-primary': '#F5F6F7',
      '--ink-secondary': '#C4C7CC',
      '--ink-muted': '#828791',
      '--ink-accent': '#00A3D9',
      '--color-primary': '#0087B5',
      '--color-primary-hover': '#009CD1',
      '--color-primary-fg': '#FFFFFF',
      '--color-danger': '#F04438',
      '--color-warning': '#F79009',
      '--color-success': '#12B76A',
      '--press-registration': '#00A3D9',
      '--press-bleed': 'rgba(0, 163, 217, 0.3)'
    }
  },
  'letterpress-craft': {
    id: 'letterpress-craft',
    name: 'Artisanal Letterpress',
    description: 'Rustic flax pulp stock with deep mechanical impression and fiery Heidelberg vermilion.',
    stockType: 'Crane’s Lettra Pearl White (600gsm 100% Cotton)',
    inkProfile: 'Oil-Based Vermilion #199 & Hand-Ground Bone Black',
    cssVariables: {
      '--surface-canvas': '#F4EFE6',
      '--surface-card': '#FCFAF6',
      '--surface-muted': '#E9E2D5',
      '--surface-raised': '#FFFFFF',
      '--surface-overlay': 'rgba(244, 239, 230, 0.95)',
      '--border-hairline': 'rgba(80, 50, 30, 0.16)',
      '--border-strong': 'rgba(80, 50, 30, 0.45)',
      '--border-focus': '#B8321B',
      '--ink-primary': '#221914',
      '--ink-secondary': '#4A3B32',
      '--ink-muted': '#7D6A5D',
      '--ink-accent': '#B8321B',
      '--color-primary': '#B8321B',
      '--color-primary-hover': '#9B2713',
      '--color-primary-fg': '#FCFAF6',
      '--color-danger': '#B8321B',
      '--color-warning': '#C66900',
      '--color-success': '#2C5A3E',
      '--press-registration': '#B8321B',
      '--press-bleed': 'rgba(184, 50, 27, 0.35)'
    }
  },
  'cmyk-proof': {
    id: 'cmyk-proof',
    name: 'ISO D50 Proofing Booth',
    description: 'Calibrated 50% neutral viewing gray with ISO 12647-7 color patch validation standards.',
    stockType: 'Epson Proofing Paper Semi-Matte (250gsm)',
    inkProfile: 'FOGRA39 Commercial Offset Proof Gamut',
    cssVariables: {
      '--surface-canvas': '#ECECEC',
      '--surface-card': '#F7F7F7',
      '--surface-muted': '#DFDFDF',
      '--surface-raised': '#FFFFFF',
      '--surface-overlay': 'rgba(236, 236, 236, 0.95)',
      '--border-hairline': 'rgba(0, 0, 0, 0.18)',
      '--border-strong': 'rgba(0, 0, 0, 0.5)',
      '--border-focus': '#0087B5',
      '--ink-primary': '#111111',
      '--ink-secondary': '#333333',
      '--ink-muted': '#666666',
      '--ink-accent': '#D61A5E',
      '--color-primary': '#111111',
      '--color-primary-hover': '#2E2E2E',
      '--color-primary-fg': '#FFFFFF',
      '--color-danger': '#D61A5E',
      '--color-warning': '#E5B20D',
      '--color-success': '#1D4537',
      '--press-registration': '#0087B5',
      '--press-bleed': 'rgba(214, 26, 94, 0.3)'
    }
  }
};
